/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as OrthodonticsRouteImport } from './routes/orthodontics'
import { Route as MobileServiceRouteImport } from './routes/mobile-service'
import { Route as DentureClinicRouteImport } from './routes/denture-clinic'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const OrthodonticsRoute = OrthodonticsRouteImport.update({
  id: '/orthodontics',
  path: '/orthodontics',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileServiceRoute = MobileServiceRouteImport.update({
  id: '/mobile-service',
  path: '/mobile-service',
  getParentRoute: () => rootRouteImport,
} as any)
const DentureClinicRoute = DentureClinicRouteImport.update({
  id: '/denture-clinic',
  path: '/denture-clinic',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/denture-clinic': typeof DentureClinicRoute
  '/mobile-service': typeof MobileServiceRoute
  '/orthodontics': typeof OrthodonticsRoute
  '/partners': typeof PartnersRoute
  '/products': typeof ProductsRoute
  '/testimonials': typeof TestimonialsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/denture-clinic': typeof DentureClinicRoute
  '/mobile-service': typeof MobileServiceRoute
  '/orthodontics': typeof OrthodonticsRoute
  '/partners': typeof PartnersRoute
  '/products': typeof ProductsRoute
  '/testimonials': typeof TestimonialsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/denture-clinic': typeof DentureClinicRoute
  '/mobile-service': typeof MobileServiceRoute
  '/orthodontics': typeof OrthodonticsRoute
  '/partners': typeof PartnersRoute
  '/products': typeof ProductsRoute
  '/testimonials': typeof TestimonialsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/denture-clinic'
    | '/mobile-service'
    | '/orthodontics'
    | '/partners'
    | '/products'
    | '/testimonials'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/denture-clinic'
    | '/mobile-service'
    | '/orthodontics'
    | '/partners'
    | '/products'
    | '/testimonials'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/denture-clinic'
    | '/mobile-service'
    | '/orthodontics'
    | '/partners'
    | '/products'
    | '/testimonials'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DentureClinicRoute: typeof DentureClinicRoute
  MobileServiceRoute: typeof MobileServiceRoute
  OrthodonticsRoute: typeof OrthodonticsRoute
  PartnersRoute: typeof PartnersRoute
  ProductsRoute: typeof ProductsRoute
  TestimonialsRoute: typeof TestimonialsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orthodontics': {
      id: '/orthodontics'
      path: '/orthodontics'
      fullPath: '/orthodontics'
      preLoaderRoute: typeof OrthodonticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile-service': {
      id: '/mobile-service'
      path: '/mobile-service'
      fullPath: '/mobile-service'
      preLoaderRoute: typeof MobileServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/denture-clinic': {
      id: '/denture-clinic'
      path: '/denture-clinic'
      fullPath: '/denture-clinic'
      preLoaderRoute: typeof DentureClinicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DentureClinicRoute: DentureClinicRoute,
  MobileServiceRoute: MobileServiceRoute,
  OrthodonticsRoute: OrthodonticsRoute,
  PartnersRoute: PartnersRoute,
  ProductsRoute: ProductsRoute,
  TestimonialsRoute: TestimonialsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
